const EXPLORE = {
    UPDATE_ACTIVE_USERS_REQUEST: 'UPDATE_ACTIVE_USERS_REQUEST',
    UPDATE_FILTERED_ACTIVE_USERS: 'UPDATE_FILTERED_ACTIVE_USERS',
    REST_FILTERED_ACTIVE_USERS: 'REST_FILTERED_ACTIVE_USERS:',
    UPDATE_SUBSCRIBED_ID: 'UPDATE_SUBSCRIBED_ID',
    UPDATE_SUBSCRIBED_ID_USER: 'UPDATE_SUBSCRIBED_ID_USER',
};
  
export default EXPLORE;
  
