const EVENTS = {
    GET_CURRENT_EVENT_REQUEST: 'GET_CURRENT_EVENT_REQUEST',
    GET_CURRENT_EVENT_REQUEST_STARTED: 'GET_CURRENT_EVENT_REQUEST_STARTED',
    GET_CURRENT_EVENT_REQUEST_SUCCESS: 'GET_CURRENT_EVENT_REQUEST_SUCCESS',
    GET_CURRENT_EVENT_REQUEST_FAILURE: 'GET_CURRENT_EVENT_REQUEST_FAILURE',

    GET_CURRENT_EVENT_REQUEST_ON_END_REACHED: 'GET_CURRENT_EVENT_REQUEST_ON_END_REACHED',
    GET_CURRENT_EVENT_REQUEST_ON_END_REACHED_STARTED: 'GET_CURRENT_EVENT_REQUEST_ON_END_REACHED_STARTED',
    GET_CURRENT_EVENT_REQUEST_ON_END_REACHED_SUCCESS: 'GET_CURRENT_EVENT_REQUEST_ON_END_REACHED_SUCCESS',
    GET_CURRENT_EVENT_REQUEST_ON_END_REACHED_FAILURE: 'GET_CURRENT_EVENT_REQUEST_ON_END_REACHED_FAILURE',

    GET_PAST_EVENT_REQUEST: 'GET_PAST_EVENT_REQUEST',
    GET_PAST_EVENT_REQUEST_STARTED: 'GET_PAST_EVENT_REQUEST_STARTED',
    GET_PAST_EVENT_REQUEST_SUCCESS: 'GET_PAST_EVENT_REQUEST_SUCCESS',
    GET_PAST_EVENT_REQUEST_FAILURE: 'GET_PAST_EVENT_REQUEST_FAILURE',

    GET_PAST_EVENT_REQUEST_ON_END_REACHED: 'GET_PAST_EVENT_REQUEST_ON_END_REACHED',
    GET_PAST_EVENT_REQUEST_ON_END_REACHED_STARTED: 'GET_PAST_EVENT_REQUEST_ON_END_REACHED_STARTED',
    GET_PAST_EVENT_REQUEST_ON_END_REACHED_SUCCESS: 'GET_PAST_EVENT_REQUEST_ON_END_REACHED_SUCCESS',
    GET_PAST_EVENT_REQUEST_ON_END_REACHED_FAILURE: 'GET_PAST_EVENT_REQUEST_ON_END_REACHED_FAILURE',

    GET_UPCOMING_EVENT_REQUEST: 'GET_UPCOMING_EVENT_REQUEST',
    GET_UPCOMING_EVENT_REQUEST_STARTED: 'GET_UPCOMING_EVENT_REQUEST_STARTED',
    GET_UPCOMING_EVENT_REQUEST_SUCCESS: 'GET_UPCOMING_EVENT_REQUEST_SUCCESS',
    GET_UPCOMING_EVENT_REQUEST_FAILURE: 'GET_UPCOMING_EVENT_REQUEST_FAILURE',

    GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED: 'GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED',
    GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED_STARTED: 'GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED_STARTED',
    GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED_SUCCESS: 'GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED_SUCCESS',
    GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED_FAILURE: 'GET_UPCOMING_EVENT_REQUEST_ON_END_REACHED_FAILURE',

    CHANGE_EVENT_STATUS: 'CHANGE_EVENT_STATUS',
    CHANGE_EVENT_STATUS_STARTED: 'CHANGE_EVENT_STATUS_STARTED',
    CHANGE_EVENT_STATUS_SUCCESS: 'CHANGE_EVENT_STATUS_SUCCESS',
    CHANGE_EVENT_STATUS_FAILURE: 'CHANGE_EVENT_STATUS_FAILURE',
};

export default EVENTS;
