const CHECKOUT = {
    GET_PAYMENT_PLANS_REQUEST: 'GET_PAYMENT_PLANS_REQUEST',
    GET_PAYMENT_PLANS_REQUEST_STARTED: 'GET_PAYMENT_PLANS_REQUEST_STARTED',
    GET_PAYMENT_PLANS_REQUEST_SUCCESS: 'GET_PAYMENT_PLANS_REQUEST_SUCCESS',
    GET_PAYMENT_PLANS_REQUEST_FAILURE: 'GET_PAYMENT_PLANS_REQUEST_FAILURE',

    SET_SELECTED_PAYMENT_PLAN_ID: 'SET_SELECTED_PAYMENT_PLAN_ID',

    GET_PAYMENT_INTENT_REQUEST: 'GET_PAYMENT_INTENT_REQUEST',
    GET_PAYMENT_INTENT_REQUEST_STARTED: 'GET_PAYMENT_INTENT_REQUEST_STARTED',
    GET_PAYMENT_INTENT_REQUEST_SUCCESS: 'GET_PAYMENT_INTENT_REQUEST_SUCCESS',
    GET_PAYMENT_INTENT_REQUEST_FAILURE: 'GET_PAYMENT_INTENT_REQUEST_FAILURE',
};

export default CHECKOUT;
