const AUTH = {
    LOGIN: 'LOGIN',
    LOGIN_STARTED: 'LOGIN_STARTED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    GENERATE_TOKEN: 'GENERATE_TOKEN',
    GENERATE_TOKEN_STARTED: 'GENERATE_TOKEN_STARTED',
    GENERATE_TOKEN_SUCCESS: 'GENERATE_TOKEN_SUCCESS',
    GENERATE_TOKEN_FAILURE: 'GENERATE_TOKEN_FAILURE',

    FETCH_USER_DATA: 'FETCH_USER_DATA',
    FETCH_USER_DATA_STARTED: 'FETCH_USER_DATA_STARTED',
    FETCH_USER_DATA_SUCCESS: 'FETCH_USER_DATA_SUCCESS',
    FETCH_USER_DATA_FAILURE: 'FETCH_USER_DATA_FAILURE',
    
    SIGNUP: 'SIGNUP',
    SIGNUP_STARTED: 'SIGNUP_STARTED',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',

    LOGOUT: 'LOGOUT',
    LOGOUT_STARTED: 'LOGOUT_STARTED',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    RESET_PASSWORD: 'RESET_PASSWORD',
    RESET_PASSWORD_STARTED: 'RESET_PASSWORD_STARTED',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

    RESET_AUTH_REDUCER: 'RESET_AUTH_REDUCER'
};
  
export default AUTH;
  
