const HOME = {
    UPDATE_PROFILE_VIEW: 'UPDATE_PROFILE_VIEW',
    UPDATE_PROFILE_VIEW_STARTED: 'UPDATE_PROFILE_VIEW_STARTED',
    UPDATE_PROFILE_VIEW_SUCCESS: 'UPDATE_PROFILE_VIEW_SUCCESS',
    UPDATE_PROFILE_VIEW_FAILURE: 'UPDATE_PROFILE_VIEW_FAILURE',

    GET_USER_PROFILE_VISITED_BY_REQUEST: 'GET_USER_PROFILE_VISITED_BY_REQUEST',
    GET_USER_PROFILE_VISITED_BY_REQUEST_STARTED: 'GET_USER_PROFILE_VISITED_BY_REQUEST_STARTED',
    GET_USER_PROFILE_VISITED_BY_REQUEST_SUCCESS: 'GET_USER_PROFILE_VISITED_BY_REQUEST_SUCCESS',
    GET_USER_PROFILE_VISITED_BY_REQUEST_FAILURE: 'GET_USER_PROFILE_VISITED_BY_REQUEST_FAILURE',

    GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED:
        'GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED',
    GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED_STARTED:
        'GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED_STARTED',
    GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED_SUCCESS:
        'GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED_SUCCESS',
    GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED_FAILURE:
        'GET_USER_PROFILE_VISITED_BY_REQUEST_ON_END_REACHED_FAILURE',

    GET_DIL_RECEIVED_USERS_REQUEST: 'GET_DIL_RECEIVED_USERS_REQUEST',
    GET_DIL_RECEIVED_USERS_REQUEST_STARTED: 'GET_DIL_RECEIVED_USERS_REQUEST_STARTED',
    GET_DIL_RECEIVED_USERS_REQUEST_SUCCESS: 'GET_DIL_RECEIVED_USERS_REQUEST_SUCCESS',
    GET_DIL_RECEIVED_USERS_REQUEST_FAILURE: 'GET_DIL_RECEIVED_USERS_REQUEST_FAILURE',

    GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED: 'GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED',
    GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED_STARTED: 'GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED_STARTED',
    GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED_SUCCESS: 'GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED_SUCCESS',
    GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED_FAILURE: 'GET_DIL_RECEIVED_USERS_REQUEST_ON_END_REACHED_FAILURE',

    SET_SELECTED_USER: 'SET_SELECTED_USER',

    SEND_LIKE_SENTIMENT: 'SEND_LIKE_SENTIMENT',
    SEND_DISLIKE_SENTIMENT: 'SEND_DISLIKE_SENTIMENT',
    OPEN_CHAT_WITH_USER: 'OPEN_CHAT_WITH_USER'
};

export default HOME;
