const NavigatorPath = {
    NAVIGATOR_AUTH: 'NAVIGATOR_AUTH',
    NAVIGATOR_PROTECTED: 'NAVIGATOR_PROTECTED',
    NAVIGATOR_WELCOME: 'NAVIGATOR_WELCOME',
    Login: 'Login',
    Intro: 'Intro',
    Signup: 'Signup',
    ForgotPassword: 'ForgotPassword',
    Dashboard: 'Dashboard',
    AuthWelcome: 'AuthWelcome',
    ExploreStack: 'ExploreStack',
    ChatsStack: 'ChatsStack',
    EventsStack: 'EventsStack',
    SettingsStack: 'SettingsStack',
    HomeStack: 'HomeStack',
    FindMatch: 'FindMatch',
    ChatListing: 'ChatListing',
    CurrentEvents: 'CurrentEvents',
    PastEvents: 'PastEvents',
    UpcomingEvents: 'UpcomingEvents',
    SettingsDetails: 'SettingsDetails',
    OtpVerification: 'OtpVerification',
    SignupSuccessful: 'SignupSuccessful',
    PaymentCheckout: 'PaymentCheckout',
    CheckoutSucceed: 'CheckoutSucceed',
    CheckoutFailed: 'CheckoutFailed',
    PaymentPlans: 'PaymentPlans',
    UserDetails: 'UserDetails',
    UnderConstruction: 'UnderConstruction',
    SettingsMenu: 'SettingsMenu',
    DilConnectUsers: 'DilConnectUsers',
    CometChatMessages: 'CometChatMessages'
};

export default NavigatorPath;
